class AllIntents:
    def __init__(self):
        self.all_intents = [
            {"package_name": "android.intent.action.BOOT_COMPLETED", "name": "BOOT_COMPLETED"},
            {"package_name": "android.intent.action.PACKAGE_REPLACED", "name": "PACKAGE_REPLACED"},
            {"package_name": "android.intent.action.SEND_MULTIPLE", "name": "SEND_MULTIPLE"},
            {"package_name": "android.intent.action.TIME_SET", "name": "TIME_SET"},
            {"package_name": "android.intent.action.PACKAGE_REMOVED", "name": "PACKAGE_REMOVED"},
            {"package_name": "android.intent.action.TIMEZONE_CHANGED", "name": "TIMEZONE_CHANGED"},
            {"package_name": "android.intent.action.ACTION_POWER_DISCONNECTED", "name": "ACTION_POWER_DISCONNECTED"},
            {"package_name": "android.intent.action.PACKAGE_ADDED", "name": "PACKAGE_ADDED"},
            {"package_name": "android.intent.action.ACTION_SHUTDOWN", "name": "ACTION_SHUTDOWN"},
            {"package_name": "android.intent.action.PACKAGE_DATA_CLEARED", "name": "PACKAGE_DATA_CLEARED"},
            {"package_name": "android.intent.action.PACKAGE_CHANGED", "name": "PACKAGE_CHANGED"},
            {"package_name": "android.intent.action.NEW_OUTGOING_CALL", "name": "NEW_OUTGOING_CALL"},
            {"package_name": "android.intent.action.SENDTO", "name": "SENDTO"},
            {"package_name": "android.intent.action.CALL", "name": "CALL"},
            {"package_name": "android.intent.action.SCREEN_ON", "name": "SCREEN_ON"},
            {"package_name": "android.intent.action.BATTERY_OKAY", "name": "BATTERY_OKAY"},
            {"package_name": "android.intent.action.PACKAGE_RESTARTED", "name": "PACKAGE_RESTARTED"},
            {"package_name": "android.intent.action.CALL_BUTTON", "name": "CALL_BUTTON"},
            {"package_name": "android.intent.action.SCREEN_OFF", "name": "SCREEN_OFF"},
            {"package_name": "intent.action.RUN", "name": "RUN"},
            {"package_name": "android.intent.action.SET_WALLPAPER", "name": "SET_WALLPAPER"},
            {"package_name": "android.intent.action.BATTERY_LOW", "name": "BATTERY_LOW"},
            {"package_name": "android.intent.action.ACTION_POWER_CONNECTED", "name": "ACTION_POWER_CONNECTED"},
        ]
