import numpy as np


class AllAppPermissions:
    def __init__(self):
        self.train_data = None
        self.all_permissions = [
            {"name": "ACCEPT_HANDOVER"},
            {"name": "ACCESS_BACKGROUND_LOCATION"},
            {"name": "ACCESS_CHECKIN_PROPERTIES"},
            {"name": "ACCESS_COARSE_LOCATION"},
            {"name": "ACCESS_FINE_LOCATION"},
            {"name": "ACCESS_LOCATION_EXTRA_COMMANDS"},
            {"name": "ACCESS_MEDIA_LOCATION"},
            {"name": "ACCESS_NETWORK_STATE"},
            {"name": "ACCESS_NOTIFICATION_POLICY"},
            {"name": "ACCESS_WIFI_STATE"},
            {"name": "ACCOUNT_MANAGER"},
            {"name": "ACTIVITY_RECOGNITION"},
            {"name": "ADD_VOICEMAIL"},
            {"name": "ANSWER_PHONE_CALLS"},
            {"name": "BATTERY_STATS"},
            {"name": "BIND_ACCESSIBILITY_SERVICE"},
            {"name": "BIND_APPWIDGET"},
            {"name": "BIND_AUTOFILL_SERVICE"},
            {"name": "BIND_CALL_REDIRECTION_SERVICE"},
            {"name": "BIND_CARRIER_MESSAGING_CLIENT_SERVICE"},
            {"name": "BIND_CARRIER_MESSAGING_SERVICE"},
            {"name": "BIND_CARRIER_SERVICES"},
            {"name": "BIND_CHOOSER_TARGET_SERVICE"},
            {"name": "BIND_CONDITION_PROVIDER_SERVICE"},
            {"name": "BIND_CONTROLS"},
            {"name": "BIND_DEVICE_ADMIN"},
            {"name": "BIND_DREAM_SERVICE"},
            {"name": "BIND_INCALL_SERVICE"},
            {"name": "BIND_INPUT_METHOD"},
            {"name": "BIND_MIDI_DEVICE_SERVICE"},
            {"name": "BIND_NFC_SERVICE"},
            {"name": "BIND_NOTIFICATION_LISTENER_SERVICE"},
            {"name": "BIND_PRINT_SERVICE"},
            {"name": "BIND_QUICK_ACCESS_WALLET_SERVICE"},
            {"name": "BIND_QUICK_SETTINGS_TILE"},
            {"name": "BIND_REMOTEVIEWS"},
            {"name": "BIND_SCREENING_SERVICE"},
            {"name": "BIND_TELECOM_CONNECTION_SERVICE"},
            {"name": "BIND_TEXT_SERVICE"},
            {"name": "BIND_TV_INPUT"},
            {"name": "BIND_VISUAL_VOICEMAIL_SERVICE"},
            {"name": "BIND_VOICE_INTERACTION"},
            {"name": "BIND_VPN_SERVICE"},
            {"name": "BIND_VR_LISTENER_SERVICE"},
            {"name": "BIND_WALLPAPER"},
            {"name": "BLUETOOTH"},
            {"name": "BLUETOOTH_ADMIN"},
            {"name": "BLUETOOTH_PRIVILEGED"},
            {"name": "BODY_SENSORS"},
            {"name": "BROADCAST_PACKAGE_REMOVED"},
            {"name": "BROADCAST_SMS"},
            {"name": "BROADCAST_STICKY"},
            {"name": "BROADCAST_WAP_PUSH"},
            {"name": "CALL_COMPANION_APP"},
            {"name": "CALL_PHONE"},
            {"name": "CALL_PRIVILEGED"},
            {"name": "CAMERA"},
            {"name": "CAPTURE_AUDIO_OUTPUT"},
            {"name": "CHANGE_COMPONENT_ENABLED_STATE"},
            {"name": "CHANGE_CONFIGURATION"},
            {"name": "CHANGE_NETWORK_STATE"},
            {"name": "CHANGE_WIFI_MULTICAST_STATE"},
            {"name": "CHANGE_WIFI_STATE"},
            {"name": "CLEAR_APP_CACHE"},
            {"name": "CONTROL_LOCATION_UPDATES"},
            {"name": "DELETE_CACHE_FILES"},
            {"name": "DELETE_PACKAGES"},
            {"name": "DIAGNOSTIC"},
            {"name": "DISABLE_KEYGUARD"},
            {"name": "DUMP"},
            {"name": "EXPAND_STATUS_BAR"},
            {"name": "FACTORY_TEST"},
            {"name": "FOREGROUND_SERVICE"},
            {"name": "GET_ACCOUNTS"},
            {"name": "GET_ACCOUNTS_PRIVILEGED"},
            {"name": "GET_PACKAGE_SIZE"},
            {"name": "GET_TASKS"},
            {"name": "GLOBAL_SEARCH"},
            {"name": "INSTALL_LOCATION_PROVIDER"},
            {"name": "INSTALL_PACKAGES"},
            {"name": "INSTALL_SHORTCUT"},
            {"name": "INSTANT_APP_FOREGROUND_SERVICE"},
            {"name": "INTERACT_ACROSS_PROFILES"},
            {"name": "INTERNET"},
            {"name": "KILL_BACKGROUND_PROCESSES"},
            {"name": "LOADER_USAGE_STATS"},
            {"name": "LOCATION_HARDWARE"},
            {"name": "MANAGE_DOCUMENTS"},
            {"name": "MANAGE_EXTERNAL_STORAGE"},
            {"name": "MANAGE_OWN_CALLS"},
            {"name": "MASTER_CLEAR"},
            {"name": "MEDIA_CONTENT_CONTROL"},
            {"name": "MODIFY_AUDIO_SETTINGS"},
            {"name": "MODIFY_PHONE_STATE"},
            {"name": "MOUNT_FORMAT_FILESYSTEMS"},
            {"name": "MOUNT_UNMOUNT_FILESYSTEMS"},
            {"name": "NFC"},
            {"name": "NFC_PREFERRED_PAYMENT_INFO"},
            {"name": "NFC_TRANSACTION_EVENT"},
            {"name": "PACKAGE_USAGE_STATS"},
            {"name": "PERSISTENT_ACTIVITY"},
            {"name": "PROCESS_OUTGOING_CALLS"},
            {"name": "QUERY_ALL_PACKAGES"},
            {"name": "READ_CALENDAR"},
            {"name": "READ_CALL_LOG"},
            {"name": "READ_CONTACTS"},
            {"name": "READ_EXTERNAL_STORAGE"},
            {"name": "READ_INPUT_STATE"},
            {"name": "READ_LOGS"},
            {"name": "READ_PHONE_NUMBERS"},
            {"name": "READ_PHONE_STATE"},
            {"name": "READ_PRECISE_PHONE_STATE"},
            {"name": "READ_SMS"},
            {"name": "READ_SYNC_SETTINGS"},
            {"name": "READ_SYNC_STATS"},
            {"name": "READ_VOICEMAIL"},
            {"name": "REBOOT"},
            {"name": "RECEIVE_BOOT_COMPLETED"},
            {"name": "RECEIVE_MMS"},
            {"name": "RECEIVE_SMS"},
            {"name": "RECEIVE_WAP_PUSH"},
            {"name": "RECORD_AUDIO"},
            {"name": "REORDER_TASKS"},
            {"name": "REQUEST_COMPANION_RUN_IN_BACKGROUND"},
            {"name": "REQUEST_COMPANION_USE_DATA_IN_BACKGROUND"},
            {"name": "REQUEST_DELETE_PACKAGES"},
            {"name": "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"},
            {"name": "REQUEST_INSTALL_PACKAGES"},
            {"name": "REQUEST_PASSWORD_COMPLEXITY"},
            {"name": "RESTART_PACKAGES"},
            {"name": "SEND_RESPOND_VIA_MESSAGE"},
            {"name": "SEND_SMS"},
            {"name": "SET_ALARM"},
            {"name": "SET_ALWAYS_FINISH"},
            {"name": "SET_ANIMATION_SCALE"},
            {"name": "SET_DEBUG_APP"},
            {"name": "SET_PREFERRED_APPLICATIONS"},
            {"name": "SET_PROCESS_LIMIT"},
            {"name": "SET_TIME"},
            {"name": "SET_TIME_ZONE"},
            {"name": "SET_WALLPAPER"},
            {"name": "SET_WALLPAPER_HINTS"},
            {"name": "SIGNAL_PERSISTENT_PROCESSES"},
            {"name": "SMS_FINANCIAL_TRANSACTIONS"},
            {"name": "START_VIEW_PERMISSION_USAGE"},
            {"name": "STATUS_BAR"},
            {"name": "SYSTEM_ALERT_WINDOW"},
            {"name": "TRANSMIT_IR"},
            {"name": "UNINSTALL_SHORTCUT"},
            {"name": "UPDATE_DEVICE_STATS"},
            {"name": "USE_BIOMETRIC"},
            {"name": "USE_FINGERPRINT"},
            {"name": "USE_FULL_SCREEN_INTENT"},
            {"name": "USE_SIP"},
            {"name": "VIBRATE"},
            {"name": "WAKE_LOCK"},
            {"name": "WRITE_APN_SETTINGS"},
            {"name": "WRITE_CALENDAR"},
            {"name": "WRITE_CALL_LOG"},
            {"name": "WRITE_CONTACTS"},
            {"name": "WRITE_EXTERNAL_STORAGE"},
            {"name": "WRITE_GSERVICES"},
            {"name": "WRITE_SECURE_SETTINGS"},
            {"name": "WRITE_SETTINGS"},
            {"name": "WRITE_SYNC_SETTINGS"},
            {"name": "WRITE_VOICEMAIL"}
        ]
        self.all_permission_names = ['android.permission.' + permission["name"] for permission in self.all_permissions]

    def format_data_array(self, all_data):
        all_train_data = []
        if len(all_data) != 0:
            for all_permission_item in self.all_permission_names:
                if all_permission_item in all_data:
                    all_train_data.append(1)
                else:
                    all_train_data.append(0)

        print(all_train_data)
        self.train_data = np.array(all_train_data)
